import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from './util/SessionProvider'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
       <SessionProvider session={session}>
         {children}
       </SessionProvider>
      </body>
    </html>
  );
}
